// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGtpETo58by7ZLiTxPcunb2sECErI5RwY',
    appId: '1:747001907939:android:f4ab8ee05972b5d37813d6',
    messagingSenderId: '747001907939',
    projectId: 'speakingnotes-5e2b5',
    databaseURL: 'https://speakingnotes-5e2b5-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'speakingnotes-5e2b5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgWL_kBPOq9wtI-myv-z_SQVNlmUwpobk',
    appId: '1:747001907939:ios:2ae8a1124449dc3f7813d6',
    messagingSenderId: '747001907939',
    projectId: 'speakingnotes-5e2b5',
    databaseURL: 'https://speakingnotes-5e2b5-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'speakingnotes-5e2b5.firebasestorage.app',
    iosBundleId: 'com.ozlemtonkal.speakingnotes',
  );

}