// Mocks generated by Mockito 5.4.6 from annotations
// in speaking_notes/test/features/category/presentation/bloc/category_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:speaking_notes/features/category/domain/models/category.dart'
    as _i5;
import 'package:speaking_notes/features/category/domain/repositories/category_repository.dart'
    as _i2;
import 'package:speaking_notes/features/category/domain/usecases/create_category_usecase.dart'
    as _i6;
import 'package:speaking_notes/features/category/domain/usecases/delete_category_usecase.dart'
    as _i8;
import 'package:speaking_notes/features/category/domain/usecases/get_all_categories_usecase.dart'
    as _i3;
import 'package:speaking_notes/features/category/domain/usecases/update_category_usecase.dart'
    as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCategoryRepository_0 extends _i1.SmartFake
    implements _i2.CategoryRepository {
  _FakeCategoryRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetAllCategoriesUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetAllCategoriesUseCase extends _i1.Mock
    implements _i3.GetAllCategoriesUseCase {
  MockGetAllCategoriesUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CategoryRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeCategoryRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.CategoryRepository);

  @override
  _i4.Future<List<_i5.Category>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i4.Future<List<_i5.Category>>.value(<_i5.Category>[]),
          )
          as _i4.Future<List<_i5.Category>>);
}

/// A class which mocks [CreateCategoryUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockCreateCategoryUseCase extends _i1.Mock
    implements _i6.CreateCategoryUseCase {
  MockCreateCategoryUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CategoryRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeCategoryRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.CategoryRepository);

  @override
  _i4.Future<void> call(_i5.Category? category) =>
      (super.noSuchMethod(
            Invocation.method(#call, [category]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [UpdateCategoryUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateCategoryUseCase extends _i1.Mock
    implements _i7.UpdateCategoryUseCase {
  MockUpdateCategoryUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CategoryRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeCategoryRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.CategoryRepository);

  @override
  _i4.Future<void> call(_i5.Category? category) =>
      (super.noSuchMethod(
            Invocation.method(#call, [category]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [DeleteCategoryUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeleteCategoryUseCase extends _i1.Mock
    implements _i8.DeleteCategoryUseCase {
  MockDeleteCategoryUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CategoryRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeCategoryRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.CategoryRepository);

  @override
  _i4.Future<void> call(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#call, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

