// Mocks generated by Mockito 5.4.6 from annotations
// in speaking_notes/test/features/note/presentation/bloc/note_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:speaking_notes/features/note/domain/models/note.dart' as _i5;
import 'package:speaking_notes/features/note/domain/repositories/note_repository.dart'
    as _i2;
import 'package:speaking_notes/features/note/domain/usecases/create_note_usecase.dart'
    as _i7;
import 'package:speaking_notes/features/note/domain/usecases/delete_note_usecase.dart'
    as _i8;
import 'package:speaking_notes/features/note/domain/usecases/get_all_notes_usecase.dart'
    as _i3;
import 'package:speaking_notes/features/note/domain/usecases/get_notes_by_category_usecase.dart'
    as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeNoteRepository_0 extends _i1.SmartFake
    implements _i2.NoteRepository {
  _FakeNoteRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetAllNotesUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetAllNotesUseCase extends _i1.Mock
    implements _i3.GetAllNotesUseCase {
  MockGetAllNotesUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.NoteRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeNoteRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.NoteRepository);

  @override
  _i4.Future<List<_i5.Note>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i4.Future<List<_i5.Note>>.value(<_i5.Note>[]),
          )
          as _i4.Future<List<_i5.Note>>);
}

/// A class which mocks [GetNotesByCategoryUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetNotesByCategoryUseCase extends _i1.Mock
    implements _i6.GetNotesByCategoryUseCase {
  MockGetNotesByCategoryUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.NoteRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeNoteRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.NoteRepository);

  @override
  _i4.Future<List<_i5.Note>> call(String? categoryId) =>
      (super.noSuchMethod(
            Invocation.method(#call, [categoryId]),
            returnValue: _i4.Future<List<_i5.Note>>.value(<_i5.Note>[]),
          )
          as _i4.Future<List<_i5.Note>>);
}

/// A class which mocks [CreateNoteUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockCreateNoteUseCase extends _i1.Mock implements _i7.CreateNoteUseCase {
  MockCreateNoteUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.NoteRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeNoteRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.NoteRepository);

  @override
  _i4.Future<void> call(_i5.Note? note) =>
      (super.noSuchMethod(
            Invocation.method(#call, [note]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [DeleteNoteUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeleteNoteUseCase extends _i1.Mock implements _i8.DeleteNoteUseCase {
  MockDeleteNoteUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.NoteRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeNoteRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.NoteRepository);

  @override
  _i4.Future<void> call(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#call, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
